AllCops:
  TargetRubyVersion: 2.7.1
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - ".gems/**/*"
    - "config/**/*"
    - "coverage/**/*"

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Enabled: true

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Basically there are two different styles:
  #
  # `nested` - have each child on a separate line
  #   class Foo
  #     class Bar
  #     end
  #   end
  #
  # `compact` - combine definitions as much as possible
  #   class Foo::Bar
  #   end
  #
  # The compact style is only forced, for classes / modules with one child.
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/DateTime:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Style/Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Style/RescueStandardError:
  Enabled: false
